[project]
name = "paleo-labels"
version = "0.0.1"
authors = [
  {name = "AFg6K7h4fhy2", email = "AFg6K7h4fhy2 <127630341+AFg6K7h4fhy2@users.noreply.github.com>"},
]
description = "Tools for the author to facilitate various tasks in paleontological work, including specimen labels, systematics organization, measurement grids, and imaging utilities."
readme = "README.md"
license = "Apache-2.0"
keywords = ["python", "geology", "paleontology", "chronostratigraphy"]
requires-python = ">=3.13"

[project.urls]
Repository = "https://github.com/AFg6K7h4fhy2/paleo-labels"
Issues = "https://github.com/AFg6K7h4fhy2/paleo-labels/issues"
"Author GitHub" = "https://github.com/AFg6K7h4fhy2/"

[tool.ruff.lint.mccabe]
max-complexity = 15
